#ifndef ENTITYTYPES_H_INCLUDED
#define ENTITYTYPES_H_INCLUDED

#include "../common.h"

#define TINDEX_NOTHING 0
#define TINDEX_ALL 1
#define TINDEX_PLAYER 2
#define TINDEX_GOOMBA 3
#define TINDEX_KOOPA 4
#define TINDEX_MUSHROOM 14
#define TINDEX_DECOR 6
#define TINDEX_GROUND 7
#define TINDEX_BRICK 8
#define TINDEX_SWITCH 9
#define TINDEX_ITEM 5
#define TINDEX_STATIC 10
#define TINDEX_ENEMY 11
#define TINDEX_DYNAMIC 12
#define TINDEX_BLOCK 13
#define TINDEX_PROJECTILE 15
#define TINDEX_TRIGGER 16
#define TINDEX_TRIGGER_HP 160
#define TINDEX_TRIGGER_DIALOG 161
#define TINDEX_TRIGGER_END 162

#define ENTMASK_S_AND_D (0x01EF)
#define ENTMASK_PROJECTILE (0x0100)
#define ENTMASK_TRIGGER (0x0200)
#define ENTMASK_PLAYER (0x0001)

#define TYPE_TINDEXCOUNT 17
#define TYPE_TYPE unsigned short

#endif // ENTITYTYPES_H_INCLUDED
